### ISSUE TITLE
python 3.11 update 

### ISSUE THREAD

**Issue by enduser001** [fHDHR/fHDHR#337]
`Traceback (most recent call last):
  File "/Users/plex/Documents/plex-addons/fHDHR/main.py", line 62, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/plex/Documents/plex-addons/fHDHR/fHDHR/cli/run.py", line 180, in main
    returned_code = start(args, script_dir, fhdhr_time, fHDHR_web, deps)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/plex/Documents/plex-addons/fHDHR/fHDHR/cli/run.py", line 137, in start
    return run(settings, fhdhr_time, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/plex/Documents/plex-addons/fHDHR/fHDHR/cli/run.py", line 42, in run
    fhdhrweb = fHDHR_web.fHDHR_HTTP_Server(fhdhr)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/plex/Documents/plex-addons/fHDHR/fHDHR_web/__init__.py", line 62, in __init__
    self.fhdhr.app.before_first_request(self.before_first_request)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Flask' object has no attribute 'before_first_request'. Did you mean: `'_got_first_request'?``

Broke my  fHDHR when I updated python to 3.11 when I upgraded my FFMPEG to version 6.

I commented out line 62 of fHDHR_web/__init__.py and it appears to work, but I am not sure about the unintended consequences.

**Comment by deathbybandaid** [comment]
the ffmpeg version doesn't cause this issue. you will want to revert your version of python, as it's not compatible.
